# This is the 1Password SSH agent config file, which allows you to customize the
# behavior of the SSH agent running on this machine.
#
# You can use it to:
# * Enable keys from other vaults than the Private vault
# * Control the order in which keys are offered to SSH servers
#
# EXAMPLE
#
# By default, all keys in your Private vault(s) are enabled:
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can enable more keys by adding more `[[ssh-keys]]` entries.
# For example, to first enable item "My SSH Key" from "My Custom Vault":
#
#  [[ssh-keys]]
#  item = "My SSH Key"
#  vault = "My Custom Vault"
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can test the result by running:
#
#  SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l
#
# More examples can be found here:
#  https://developer.1password.com/docs/ssh/agent/config

# Add My 1Password Curve25519 key
[[ssh-keys]]
item = "op_id_ed25519"
vault = "Private"

# Add my 1Password RSA key
[[ssh-keys]]
item = "op_id_rsa"
vault = "Private"

# Add My Personal Curve25519 Key
[[ssh-keys]]
item = "id_ed25519"
vault = "Private"

# Add My Legacy RSA Key Last
[[ssh-keys]]
item = "id_rsa"
vault = "Private"

# Example Entries Below
# Add my Git authentication key from my Work vault
#[[ssh-keys]]
#item = "Git Authentication Key"
#vault = "Work"

# Add my Git signing key from my Work vault
#[[ssh-keys]]
#item = "Git Signing Key"
#vault = "Work"

# Then add all keys from my Private vault
#[[ssh-keys]]
#vault = "Private"
#account = "Wendy Appleseed's Family"


